export const services = [
  {
    icon: "scan",
    title: "Factory Diagnostics",
    desc: "Nissan CONSULT 3+ computer diagnostics with 172-point health scan and printed report.",
    price: "from EGP 750",
    tag: "45 min",
  },
  {
    icon: "oil",
    title: "Express Maintenance",
    desc: "Genuine 5W-30 + filter, 10k service in 60 minutes. Free wash & torque check included.",
    price: "from EGP 2,900",
    tag: "60 min",
  },
  {
    icon: "brake",
    title: "Brakes & Suspension",
    desc: "OEM pads, discs, shocks tuned for Egyptian roads — Cairo potholes approved.",
    price: "from EGP 1,800",
    tag: "Same day",
  },
  {
    icon: "ac",
    title: "A/C Desert Cooling",
    desc: "Freon recovery, compressor test, cabin filter + anti-bacterial treatment for 50°C summers.",
    price: "from EGP 1,200",
    tag: "2 hrs",
  },
  {
    icon: "body",
    title: "Body & Paint Studio",
    desc: "Computer-matched paint booth, PDR dent removal, and insurance-direct repairs.",
    price: "Free quote",
    tag: "3–5 days",
  },
  {
    icon: "battery",
    title: "Battery, Tires & Alignment",
    desc: "Bridgestone / Michelin fitment, 3D laser alignment, free rotation every 10k.",
    price: "from EGP 950",
    tag: "90 min",
  },
];

export const models = [
  {
    name: "Nissan Patrol",
    trim: "LE Platinum V8",
    price: "EGP 6,850,000",
    monthly: "EGP 98,500/mo",
    specs: ["405 HP", "7 Seats", "4WD"],
    tag: "Flagship",
    gradient: "from-zinc-700 to-zinc-900",
  },
  {
    name: "Nissan X-Trail",
    trim: "e-POWER e-4ORCE",
    price: "EGP 2,450,000",
    monthly: "EGP 36,900/mo",
    specs: ["213 HP Hybrid", "5+2 Seats", "AWD"],
    tag: "Hybrid",
    gradient: "from-red-950 to-zinc-900",
  },
  {
    name: "Nissan Qashqai",
    trim: "Tekna+ Turbo",
    price: "EGP 1,895,000",
    monthly: "EGP 28,400/mo",
    specs: ["158 HP", "ProPILOT", "Bose"],
    tag: "Best Seller",
    gradient: "from-amber-950 to-zinc-900",
  },
  {
    name: "Nissan Sunny",
    trim: "Super Saloon",
    price: "EGP 795,000",
    monthly: "EGP 11,900/mo",
    specs: ["1.5L Efficient", "Cruise", "Camera"],
    tag: "Value",
    gradient: "from-slate-700 to-zinc-900",
  },
  {
    name: "Nissan Navara",
    trim: "LE Double Cab 4x4",
    price: "EGP 1,650,000",
    monthly: "EGP 24,700/mo",
    specs: ["190 HP Diesel", "1T Payload", "Crawl"],
    tag: "Workhorse",
    gradient: "from-stone-700 to-zinc-900",
  },
  {
    name: "Nissan Juke",
    trim: "N-Connecta",
    price: "EGP 1,295,000",
    monthly: "EGP 19,400/mo",
    specs: ["114 HP Turbo", "360 Cam", "CarPlay"],
    tag: "Urban",
    gradient: "from-yellow-950 to-zinc-900",
  },
];

export const testimonials = [
  {
    name: "Eng. Sherif El-Masry",
    car: "Patrol 2023 • New Cairo",
    text: "Dealer-level diagnostics without the games. They sent me the full CONSULT report on WhatsApp before touching a bolt. First center I actually trust.",
    rating: 5,
  },
  {
    name: "Mona Abdelaziz",
    car: "Qashqai 2022 • Zamalek",
    text: "Booked at 9am, out by 10:15 with wash and genuine oil. The lounge has real coffee and you watch your car on screen. Brilliant.",
    rating: 5,
  },
  {
    name: "Capt. Karim Fahmy",
    car: "Navara Fleet (14 cars) • Alexandria",
    text: "They maintain our entire site fleet. Downtime dropped 70%. One invoice, one advisor, zero surprises. That's why we stay.",
    rating: 5,
  },
];
